FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# Ejecuta la aplicación Flask con run.py
CMD ["python", "run.py"]

